[package]
name = "rr"
version = "0.1.0"
authors = ["Etienne Beaulieu <ety_95@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
